site_name: 3301Docs
repo_url: "https://github.com/Rusty3141/3301Docs"
repo_name: Rusty3141/3301Docs
edit_uri: "https://github.com/Rusty3141/3301Docs/edit/main/docs"
theme:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  name: material
  custom_dir: docs/overrides
  logo: assets/images/AnonIcon.png
  favicon: assets/images/AnonIcon.ico
  font:
    text: Work Sans
    code: Source Code Pro
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to the dark theme.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to the light theme.
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/Rusty3141/3301Docs"
      name: 3301Docs on Github
    - icon: fontawesome/brands/discord
      link: "https://discordapp.com/invite/83qGbPA"
      name: CicadaSolvers on Discord
copyright: Site content under the <a href="https://github.com/Rusty3141/3301Docs/blob/main/LICENSE" target="_blank" rel="noopener">GPL-3.0 License</a>
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - git-authors:
      fallback_to_empty: false
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - lightgallery:
      show_description_in_lightgallery: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
