name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: GitHub Pages deployment
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-authors-plugin
      - name: Install custom lightGallery version
        working-directory: ./plugins/lightgallery-multi-image
        run: python setup.py install
      - run: mkdocs gh-deploy --force
