name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: GitHub Pages deployment
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-material
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install filetype
      - run: pip install pillow
      - run: pip install titlecase
      - name: Generate thumbnails for large images
        working-directory: ./tools
        run: python generate_thumbnails.py
      - name: Install custom lightGallery version
        working-directory: ./plugins/lightgallery-markdown-extended
        run: python setup.py install
      - name: Install custom title casing plugin
        working-directory: ./plugins/title-casing
        run: python setup.py install
      - run: mkdocs gh-deploy --force
